openapi: 3.0.1
info:
  title: ResearchGroup-ComputerVision
  description: API Definition of ResearchGroup-ComputerVision
  version: 1.0.0
servers:
- url: http://localhost:8290/research-groups/v1/vision
- url: https://localhost:8253/research-groups/v1/vision
paths:
  /:
    get:
      responses:
        default:
          description: Default response
  /publications:
    get:
      responses:
        default:
          description: Default response
